# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_page_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chat_page_ui(object):
    def setupUi(self, chat_page_ui):
        chat_page_ui.setObjectName("chat_page_ui")
        chat_page_ui.resize(978, 565)
        self.verticalLayout = QtWidgets.QVBoxLayout(chat_page_ui)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(chat_page_ui)
        self.frame.setMinimumSize(QtCore.QSize(0, 51))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ping = QtWidgets.QLabel(self.frame)
        self.ping.setAlignment(QtCore.Qt.AlignCenter)
        self.ping.setObjectName("ping")
        self.horizontalLayout_2.addWidget(self.ping)
        self.token = QtWidgets.QLabel(self.frame)
        self.token.setAlignment(QtCore.Qt.AlignCenter)
        self.token.setObjectName("token")
        self.horizontalLayout_2.addWidget(self.token)
        self.sys_comboBox = ComboBox(self.frame)
        self.sys_comboBox.setObjectName("sys_comboBox")
        self.horizontalLayout_2.addWidget(self.sys_comboBox)
        self.comboBox = ComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame)
        self.bot_html = QtWebEngineWidgets.QWebEngineView(chat_page_ui)
        self.bot_html.setObjectName("bot_html")
        self.verticalLayout.addWidget(self.bot_html)
        self.user = QtWidgets.QWidget(chat_page_ui)
        self.user.setMinimumSize(QtCore.QSize(0, 61))
        self.user.setMaximumSize(QtCore.QSize(16777215, 61))
        self.user.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"\n"
"    font: 20px \'Cascadia Code\';\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}\n"
"QFrame {\n"
"    background-color: #333333;\n"
"    color: #cccccc;\n"
"    font: 20px \'Cascadia Code\';\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}")
        self.user.setObjectName("user")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.user)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_text = QtWidgets.QTextEdit(self.user)
        self.user_text.setMinimumSize(QtCore.QSize(0, 43))
        self.user_text.setMaximumSize(QtCore.QSize(16777215, 43))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.user_text.setFont(font)
        self.user_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_text.setObjectName("user_text")
        self.horizontalLayout.addWidget(self.user_text)
        self.menu_btn = QtWidgets.QPushButton(self.user)
        self.menu_btn.setMinimumSize(QtCore.QSize(31, 30))
        self.menu_btn.setMaximumSize(QtCore.QSize(31, 30))
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    font: 15px \'Microsoft YaHei\';\n"
"    border: transparent;\n"
"    border-radius: 6px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:pressed:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(204, 204, 204);\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.menu_btn.setText("")
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout.addWidget(self.menu_btn)
        self.send_btn = QtWidgets.QPushButton(self.user)
        self.send_btn.setMinimumSize(QtCore.QSize(31, 30))
        self.send_btn.setMaximumSize(QtCore.QSize(31, 30))
        self.send_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    font: 15px \'Microsoft YaHei\';\n"
"    border: transparent;\n"
"    border-radius: 6px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:pressed:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(204, 204, 204);\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.send_btn.setText("")
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout.addWidget(self.send_btn)
        self.verticalLayout.addWidget(self.user)

        self.retranslateUi(chat_page_ui)
        QtCore.QMetaObject.connectSlotsByName(chat_page_ui)

    def retranslateUi(self, chat_page_ui):
        _translate = QtCore.QCoreApplication.translate
        chat_page_ui.setWindowTitle(_translate("chat_page_ui", "Form"))
        self.ping.setText(_translate("chat_page_ui", "延迟：0ms"))
        self.token.setText(_translate("chat_page_ui", "当前Tokens：0"))
from PyQt5 import QtWebEngineWidgets
from qfluentwidgets import ComboBox
