# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chat_window(object):
    def setupUi(self, chat_window):
        chat_window.setObjectName("chat_window")
        chat_window.resize(982, 574)
        self.verticalLayout = QtWidgets.QVBoxLayout(chat_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(chat_window)
        self.frame.setMinimumSize(QtCore.QSize(0, 43))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 43))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.comboBox = ComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame)
        self.bot_html = QtWebEngineWidgets.QWebEngineView(chat_window)
        self.bot_html.setObjectName("bot_html")
        self.verticalLayout.addWidget(self.bot_html)
        self.user = QtWidgets.QWidget(chat_window)
        self.user.setMinimumSize(QtCore.QSize(0, 61))
        self.user.setMaximumSize(QtCore.QSize(16777215, 61))
        self.user.setStyleSheet("QWidget {\n"
"    background-color: #333333;\n"
"\n"
"    font: 20px \'Cascadia Code\';\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}\n"
"QFrame {\n"
"    background-color: #333333;\n"
"    color: #cccccc;\n"
"    font: 20px \'Cascadia Code\';\n"
"    border: none; \n"
"    border-radius: 8px;\n"
"}")
        self.user.setObjectName("user")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.user)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_input = QtWidgets.QTextEdit(self.user)
        self.user_input.setMinimumSize(QtCore.QSize(0, 43))
        self.user_input.setMaximumSize(QtCore.QSize(16777215, 43))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.user_input.setFont(font)
        self.user_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.user_input.setObjectName("user_input")
        self.horizontalLayout.addWidget(self.user_input)
        self.menu_btn = QtWidgets.QPushButton(self.user)
        self.menu_btn.setMinimumSize(QtCore.QSize(31, 30))
        self.menu_btn.setMaximumSize(QtCore.QSize(31, 30))
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    font: 15px \'Microsoft YaHei\';\n"
"    border: transparent;\n"
"    border-radius: 6px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:pressed:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(204, 204, 204);\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.menu_btn.setText("")
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout.addWidget(self.menu_btn)
        self.send_btn = QtWidgets.QPushButton(self.user)
        self.send_btn.setMinimumSize(QtCore.QSize(31, 30))
        self.send_btn.setMaximumSize(QtCore.QSize(31, 30))
        self.send_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(204, 204, 204);\n"
"    font: 15px \'Microsoft YaHei\';\n"
"    border: transparent;\n"
"    border-radius: 6px;\n"
"    padding: 5px 5px;\n"
"}\n"
"\n"
"QPushButton:pressed:hover {\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(204, 204, 204);\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.send_btn.setText("")
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout.addWidget(self.send_btn)
        self.verticalLayout.addWidget(self.user)

        self.retranslateUi(chat_window)
        QtCore.QMetaObject.connectSlotsByName(chat_window)

    def retranslateUi(self, chat_window):
        _translate = QtCore.QCoreApplication.translate
        chat_window.setWindowTitle(_translate("chat_window", "Form"))
        self.pushButton.setText(_translate("chat_window", "PushButton"))
        self.pushButton_2.setText(_translate("chat_window", "PushButton"))
        self.pushButton_3.setText(_translate("chat_window", "PushButton"))
from PyQt5 import QtWebEngineWidgets
from qfluentwidgets import ComboBox
